api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('product', views.productPageData, name='project-data')
]

bakerspoint/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


from company import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('api/', include('api.urls')),
    path('store/', include('store.urls')),
    path('order/',views.orderPage, name='order_page')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('<slug:name>/', views.productPage, name='product_page' ),
    path('products/<slug:slug>', views.productItem, name = 'product_item')
]

company/models.py
from django.urls import reverse
from django.db import models

# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=50, null=False)
    image = models.ImageField(upload_to='media/company')
    description = models.CharField(max_length=300, null=False)
    color = models.CharField(max_length=30, null=True)

    def imageURL(self):
        try:
            image_url = self.image.url
        except:
            image_url = ''
        return image_url

    def __str__(self) -> str:
        return self.name

store/models.py
from django.urls import reverse
from django.db import models
from django.utils.text import slugify
from company.models import Categories

# Create your models here.

#product weight chioces
WEIGHT = (
    ("500g","500g"),
    ("1kg","1kg"),
    ("2.5kg", "2.5kg"),
    ("5kg", "5kg")
)
class ProductCategories(models.Model):
    categories = models.ForeignKey(Categories, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True,blank=True)
    image = models.ImageField(upload_to='media/store/products')

    def save(self, *args, **kwargs):
   
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('products', kwargs = {'slug':self.slug})

class Product(models.Model):
    product_category = models.ForeignKey(ProductCategories, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    description = models.CharField(max_length=500)
    weight = models.CharField(max_length=10,choices=WEIGHT, default='500g')

    def __str__(self) -> str:
        return str(self.product_category)+" of "+self.weight

    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/store/products')
    alt = models.CharField(max_length=20, null=True)

    def __str__(self) -> str:
        return 'Image for '+ str(self.product)

class Reviews(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default='')
    user = models.CharField(max_length=100)
    rating = models.IntegerField()
    comment = models.CharField(max_length=100)
    show = models.BooleanField(default=False)

    def __str__(self) -> str:
        return 'review for '+self.Product


class Order(models.Model):
    customer = models.CharField(max_length=100)
    date_orderd = models.DateField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100)

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0)
    data_added = models.DateField(auto_now_add=True)

api/views.py
from store.models import Product, ProductImage
from api.sterilizer import ProductSerializer, ProductImageSerializer
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
from rest_framework.decorators import api_view

import json

@api_view(['POST'])
def productPageData(request):
    data = json.loads(request.body)
    product_name = data['name']
    product_weight = data['weight']
    product = get_object_or_404(Product, product_category=product_name, weight=product_weight)
    serial_product = ProductSerializer(product, many=False)
    images = ProductImage.objects.filter(product=product.id)
    serial_images = ProductImageSerializer(images, many=True)
    data = {'product_info':serial_product.data,'product_images':serial_images.data}
    return Response(data)

company/views.py
from django.shortcuts import render
from .models import Categories
# Create your views here.

def index(request):
    cake = Categories.objects.get(name='cakes')
    cookies = Categories.objects.get(name='cookies')
    chin_chin = Categories.objects.get(name='chin-chin')
    peanut = Categories.objects.get(name='peanut')

    context = {'cake':cake, 'cookies':cookies,'chinchin':chin_chin,
                'peanut':peanut}
    template_name = 'index.html'

    return render(request,template_name, context)

def orderPage(request):
    template_name = 'order.html'

    return render(request,template_name)

store/views.py
from itertools import product
from multiprocessing import context
from django.shortcuts import render
from django.shortcuts import get_object_or_404

# Create your views here.
from company.models import Categories
from .models import Product , ProductCategories

def productPage(request, name):
    category = Categories.objects.get(name=name)
    products = Product.objects.filter(categories=category)
    context = {'category':category, 'products':products}
    template_name = 'product_page.html'

    return render (request, template_name, context)


def productItem(request, slug):
    product = get_object_or_404(ProductCategories, slug=slug)
    context={'product':product}
    template_name = 'product.html'
    return render(request, template_name, context)

company/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../../static/css/style.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
  <title>Document</title>
</head>
{% block content %}
{% endblock content%}
<footer>
    <div class="footer-line" ></div>
    <div class="footer-content">
      <div>
        <div class="footer-content-head-section">
          <div class="footer-content-header"><h4>navigator</h4></div> 
          <span ><img name="footer-img" src="{% static 'images/right-arrow-svgrepo-com(1).svg' %}" alt=""></span>
        </div>
        <div class="footer-content-p no-display-min" name="footer-dropdown">
          <p>Sign Up</p>
          <p>Blog</p>
          <p>Products</p>
        </div>
      </div>
      <div>
        <div class="footer-content-head-section">
          <div class="footer-content-header"><h4>Help</h4></div> 
          <span ><img name="footer-img" src="{% static 'images/right-arrow-svgrepo-com(1).svg' %}" alt=""></span>
        </div>
        <div class="footer-content-p no-display-min" name="footer-dropdown">
          <p>Ordering</p>
          <p>Payments</p>
          <p>Delivery</p>
        </div>
      </div>
      <div>
        <div class="footer-content-head-section">
          <div class="footer-content-header"><h4>Socials</h4></div> 
          <span ><img name="footer-img" src="{% static 'images/right-arrow-svgrepo-com(1).svg' %}"  alt=""></span>
        </div>
        <div class="footer-content-p no-display-min" name="footer-dropdown">
          <p>E-mail</p>
          <p>Instagram</p>
          <p>Whatsapp</p>
        </div>
      </div>
    </div>
    <section class="footer-bottom">
      <div>copyrights 2015-2022</div>
      <div>Developed by winterdevelopers</div>
    </section>
  </footer>
  
  <script src="{% static 'js/script.js' %}"></script>

company/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../../static/css/register.css">
  <title>Document</title>
</head>
<body>
  <section class="form-body">
    <div class="form">
      <h2>Register</h2>
  
      <form action="">
        <div class="form-row">
          <input type="text" name="" id="" placeholder="First Name" required>
          <input type="text" name="" id="" placeholder="Last Name" required>
        </div>
        <div class="form-row">
          <input type="text" name="" id="" placeholder="Username" required>
          <input type="email" name="" id="" placeholder="Email" required>
        </div>
        <div class="form-row">
          <input type="password" name="" id="" placeholder="Password" required>
          <input type="password" name="" id="" placeholder="Confirm Password" required>
        </div>
        <div class="form-row button-row">
          <button type="submit">SIGN UP</button>
        </div>
      </form>
    </div>
  </section>
</body>
</html>

company/templates/index.html
{% extends 'base.html' %}
{% load static %}
  {% block content %}
  {% include 'navbar.html' %}
  <div class="hero-section">
    <div>
      <h1 class="heading white header-font">Bakers Point</h1>
      <p class="white">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
      <div class="btn-div1">
        <a href=""><button class="white button1">Take a Tour</button></a>
      </div>
    </div>
  </div>

  <section id="about">
    <div>
      <h1 class="about light-header">ABOUT US</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga impedit modi vel vitae eveniet odio eum reiciendis veniam. Quidem deleniti non animi ipsum debitis, vero reprehenderit numquam porro repellendus? Cum? Lorem ipsum dolor sit amet dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem cum dolor dolorem quos, quae aliquid, libero no </p>
    </div>

    <div class="img-offset">
      <img src="../static/images/bread.png" alt="Baked Bread">
      <img src="../static/images/store.png" alt="Store Door">
      <img src="../static/images/cup-cake.png" alt="Cup Cake">
    </div>
  </section>

  <section id="top-products">
    <h1 class="light-header top-product-header">Top Products</h1>

    <div class="top-product-item">
      <div>
        <img src="../static/images/chin-chin 1.png" alt="">
      
        <div>
          <span>chin-chin</span>
          <span>&#8358; 1000</span>
        </div>
      </div>
      <div>
        <img src="../static/images/chin-chin 1.png" alt="">
      
        <div>
          <span>chin-chin</span>
          <span>&#8358; 1000</span>
        </div>
      </div>
      <div>
        <img src="../static/images/chin-chin 1.png" alt="">
      
        <div>
          <span>chin-chin</span>
          <span>&#8358; 1000</span>
        </div>
      </div>
      <div>
        <img src="../static/images/chin-chin 1.png" alt="">
      
        <div>
          <span>chin-chin</span>
          <span>&#8358; 1000</span>
        </div>
      </div>
      <div>
        <img src="../static/images/chin-chin 1.png" alt="">
      
        <div>
          <span>chin-chin</span>
          <span>&#8358; 1000</span>
        </div>
      </div>
      <div>
        <img src="../static/images/chin-chin 1.png" alt="">
      
        <div>
          <span>chin-chin</span>
          <span>&#8358; 1000</span>
        </div>
      </div>
      <div>
        <img src="../static/images/chin-chin 1.png" alt="">
      
        <div>
          <span>chin-chin</span>
          <span>&#8358; 1000</span>
        </div>
      </div>
    </div>
  </section>

  <section id="bakery-menu">
    <div class="bakery-menu-title">
      <h2 class="border-h2">Bakery Menu</h2>
    </div>

    <div class="bakery-menu-cake bakery-menu bakery-menu-reverse">
      <div class="item-1">
        <h2>{{cake.name}}</h2>
        <p class="item-description">This is why I am telling you that you need more cake, but this is a demo, thank you. I hope you understand, thank you, you're welcome.</p>
        <div class="btn-div2">
          <a href="{% url 'store:product_page' cake.name %}">
            <button class="menu-button button-cake">
              <p style="align-items: center; display: flex;">View</p>
              <img src="../static/images/arrow-right.svg" alt="">
            </button>
          </a>
        </div>
      </div>
      <div class="image-1">
        <img src="{{cake.imageURL}}" alt="Chocolate & Vanilla Cake">
      </div>
    </div>

    <div class="bakery-menu-cookies bakery-menu bakery-menu-none-reverse">
      <div class="image-2">
        <img src="{{cookies.imageURL}}" alt="Cookies">
      </div>
      <div class="item-2">
        <h2>{{cookies.name}}</h2>
        <p class="item-description">This is why I am telling you that you need more cookies, but this is a demo, thank you. I hope you understand, thank you, you're welcome.</p>
        <div class="btn-div2">
          <a href="{% url 'store:product_page' cookies.name %}">
            <button class="menu-button button-cookies">
              <p style="align-items: center; display: flex;">View</p>
              <img src="../static/images/arrow-right.svg" alt="">
            </button>
          </a>
        </div>
      </div>
    </div>
    <div class="bakery-menu-chin-chin bakery-menu bakery-menu-reverse"> 
      <div class="item-2">
        <h2>{{chinchin.name}}</h2>
        <p class="item-description">This is why I am telling you that you need more cookies, but this is a demo, thank you. I hope you understand, thank you, you're welcome.</p>
        <div class="btn-div2">
          <a href="{% url 'store:product_page' chinchin.name %}">
            <button class="menu-button button-chin-chin">
              <p style="align-items: center; display: flex;">View</p>
              <img src="../static/images/arrow-right.svg" alt="">
            </button>
          </a>
        </div>
      </div>
      <div class="image-2">
        <img src="{{chinchin.imageURL}}" alt="Cookies">
      </div>
    </div>
    <div class="bakery-menu-peanut bakery-menu bakery-menu-none-reverse">
      <div class="image-2">
        <img src="{{peanut.imageURL}}" alt="Cookies">
      </div>
      <div class="item-2">
        <h2>{{peanut.name}}</h2>
        <p class="item-description">This is why I am telling you that you need more cookies, but this is a demo, thank you. I hope you understand, thank you, you're welcome.</p>
        <div class="btn-div2">
          <a href="{% url 'store:product_page' peanut.name %}">
            <button class="menu-button button-peanut">
              <p style="align-items: center; display: flex;">View</p>
              <img src="../static/images/arrow-right.svg" alt="">
            </button>
          </a>
        </div>
      </div>
    </div>
  </section>

  <section class="our-story">
    <div>
      <img src="../static/images/store.png" alt="">
    </div>
    <div>
      <p>From the south East of nigeria  in the middle 2000’s 
        Bakerspoint was first form when a the founder Nkiru
        Ezekwem started producing cup cakes.... </p>
      <div>
        <h2 class="border-h2 ">Our Story</h2>
      </div>
    </div>
  </section>

  <section class="customers-reviews">
    <h1 class="light-header ">Customer Reviews</h1>

    <div>
      <div class="customer-reviews-card bc-white">
        <img src="../static/images/reviews.png" alt="">
        <p>Lorem ipsum dolors it amet, consectetur adipisicing elit.
          Eum aspernatur asperiores.
        </p>
        <div>
          <h2>Chima okechukwu</h2>
          <div>
            <img class="review-stars" src="../static/images/star.svg" alt="">
            <img class="review-stars" src="../static/images/star.svg" alt="">
            <img class="review-stars" src="../static/images/star.svg" alt="">
            <img class="review-stars" src="../static/images/star.svg" alt="">
            <img class="review-stars" src="../static/images/star.svg" alt="">
        
          </div>
        </div>      
      </div>
      <div class="customer-reviews-card bc-white">
        <img src="../static/images/reviews.png" alt="">
        <p>Lorem ipsum dolors it amet, consectetur adipisicing elit.
          Eum aspernatur asperiores.
        </p>
        <div>
          <h2>Chima okechukwu</h2>
          <div>
            <img class="review-stars" src="../static/images/star.svg" alt="">
            <img class="review-stars"  src="../static/images/star.svg" alt="">
            <img class="review-stars" src="../static/images/star.svg" alt="">
            <img class="review-stars" src="../static/images/star.svg" alt="">
          </div>
        </div>      
      </div>
      <div class="customer-reviews-card bc-white">
          <img src="../static/images/reviews.png" alt="">
          <p>Lorem ipsum dolors it amet, consectetur adipisicing elit.
            Eum aspernatur asperiores.
          </p>
          <div>
            <h2>Chima okechukwu</h2>
            <div>
              <img class="review-stars" src="../static/images/star.svg" alt="">
              <img class="review-stars"  src="../static/images/star.svg" alt="">
              <img class="review-stars" src="../static/images/star.svg" alt="">
              <img class="review-stars" src="../static/images/star.svg" alt="">
            </div>
          </div>      
        </div>
        <div class="customer-reviews-card bc-white">
          <img src="../static/images/reviews.png" alt="">
          <p>Lorem ipsum dolors it amet, consectetur adipisicing elit.
            Eum aspernatur asperiores.
          </p>
          <div>
            <h2>Chima okechukwu</h2>
            <div>
              <img class="review-stars" src="../static/images/star.svg" alt="">
              <img class="review-stars"  src="../static/images/star.svg" alt="">
              <img class="review-stars" src="../static/images/star.svg" alt="">
              <img class="review-stars" src="../static/images/star.svg" alt="">
            </div>
          </div>      
        </div>
      </div>
    </div>
  </section>

  <section class="other">
    <div class="bc-white special other-box">
      <div><img src="../static/images/discount.svg" alt=""></div>
      <h2>SPECIAL REQUEST</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Natus a corporis fugit quasi repellat, consequatur cum distinctio 
        officia doloribus temporibus sed vel, nam velit hic</p>
        <div class="other-button">
          contact
        </div>
    </div>
    <div class="bc-white other-box">
      <h2 class="other-box-h2-border">PROMOTION</h2>
      <p>if you would like to get notified durings our
        sales and special event, subscribe to our newsletter</p>
      <form action="" method="post">
        {% csrf_token %}
        <input type="email">
        <input type="submit" value="SUBSCRIBE">
      </form>
    </div>
  </section>
  <br>
  <br>
  {% endblock %}
  <!-- <script src="{% static 'js/sctipt.js' %}"></script> -->
  <!-- <script src="../static/js/sctipt.js"></script> -->
</body>
</html>

company/templates/navbar.html
{% load static %}
<header>
    <nav>
      <div class="logo">
        <div>LOGO</div>
      </div>
      <div class="options no-display-min">
        <div>Menu</div>
        <div>About</div>
        <div>Contact</div>
      </div>
      <div class="cart">
          <img src="{% static 'images/shoppin-paper-bag-svgrepo-com.svg' %}" alt="cat-bag">
          <div>0</div>
      </div>
      <div class="nav-search no-display-min">
        <form action="" method="post">
          <input type="search">
        </form>
        <img src="{% static 'images/search-icon.svg' %}" alt="">
      </div>
      <div class="mobile-nav no-display-max" style="width:20%;">
        <img src="{% static 'images/search-icon.svg' %}" alt="" style="width:1.3rem;">
      </div>
      <div id="mobile-menu-btn" class="no-display-max mobile-nav">
        <img src="{% static 'images/hamburger-menu-svgrepo-com.svg' %}" alt="">
      </div>
      
    </nav>
    
  </header>
  
  <div id="mobile-menu" class="no-display-max">
    <div class="mobile-menu-header">
      <div>
        LOGO
      </div>
      <div id="mobile-menu-cancel-btn" class="mobile-menu-cancel-btn">
        <img src="{% static 'images/cancel.svg' %}" alt="cancel" >
      </div>
    </div>
    <div class="mobile-side-item">
      <div>
        Menu
      </div>
      <div>
        <img src="{% static 'images/right-arrow-svgrepo-com(1).svg' %}" alt="">
      </div>
    </div>
    <div class="mobile-side-item">
      <div>
        Delivery
      </div>
      <div>
        <img src="{% static 'images/right-arrow-svgrepo-com(1).svg' %}" alt="">
      </div>
    </div>
    <div class="mobile-side-item">
      <div>
        About
      </div>
      <div>
        <img src="{% static 'images/right-arrow-svgrepo-com(1).svg' %}" alt="">
      </div>
    </div>
    <div class="mobile-side-item">
      <div>
        Contact
      </div>
      <div>
        <img src="{% static 'images/right-arrow-svgrepo-com(1).svg' %}" alt="">
      </div>
    </div>
    <div class="mobile-side-item">
      <div>
        Special Order
      </div>
      <div>
        <img src="{% static 'images/right-arrow-svgrepo-com(1).svg' %}" alt="">
      </div>
    </div>
  </div>
  <script type="text/javascript">
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');
 </script>
  <div style="height:5rem;"></div> 

company/templates/order details/order.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../../static/css/order.css">
  <title>Document</title>
</head>
<body>
  <section class="main-section">
    <section class="order-details">
      <h2>Order Details</h2>
      <div class="detail-box">
        <div class="quantity">
          <h4>Total Quantity</h4>
          <p>7</p>
        </div>
        <div class="v-line"></div>
        <div class="cost">
          <h4>Total Cost</h4>
          <p>₦31,000</p>
        </div>
      </div>
    </section>
  
    <section class="shipping">
      <h2>Shipping Details</h2>
      <form action="">
        <div class="input-main">
          <div class="input-div">
            <img src="../../static/images/user.svg" alt="">
            <input type="text" name="" id="" placeholder="Name" required>
          </div>
          <div class="input-div">
            <img src="../../static/images/email.svg" alt="">
            <input type="email" name="" id="" placeholder="Email" required>
          </div>
        </div>

        <div class="input-main">
          <div class="input-div">
            <img src="../../static/images/location.svg" alt="">
            <input type="text" name="" id="" placeholder="Address" required>
          </div>
          <div class="input-div">
            <img src="../../static/images/phone.svg" alt="">
            <input type="email" name="" id="" placeholder="Phone Number" required>
          </div>
        </div>
        <div class="btn-submit">
          <button type="submit">Submit Details</button>
        </div>
      </form>
    </section>

    <div class="payment">
      <div class="btn-payment">
        <button type="submit">Make Payment</button>
      </div>
  
      <div class="payment-options">
        <img src="../../static/images/paystack-badge 1(1).svg" alt="">
      </div>
    </div>
  </section>
</body>
</html>

company/templates/order.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/style.css">
    <title>Document</title>
  </head>
<section class="order-section">
    <h2>cart</h2>
    <div class="order-line"></div>
    <div class="order-content">
        <section class="order-content-section">
            <div>
                <img src="../static/images/cup-cake.png" alt="" srcset="">
            </div>
            <div>
                <h2>
                    &#8358; 15,000
                </h2>
                <h4>cake muchines</h4>
                <p>1KG</p>
                <div class="order-quantity">
                    <div class="order-button">
                        &#8722;
                    </div>
                    <div class="order-item-qty">
                        3
                    </div>
                    <div class="order-button">
                        &#43;
                    </div>
                </div>
            </div>
        </section>
        <section class="order-content-section">
            <div>
                <img src="../static/images/bread.png" alt="" srcset="">
            </div>
            <div>
                <h2>
                    &#8358; 15,000
                </h2>
                <h4>Nigerian Bread</h4>
                <p>1KG</p>
                <div class="order-quantity">
                    <div class="order-button">
                        &#8722;
                    </div>
                    <div class="order-item-qty">
                        30
                    </div>
                    <div class="order-button">
                        &#43;
                    </div>
                </div>
            </div>
        </section>
        <section class="order-content-section">
            <div>
                <img src="../static/images/chin-chin 1.png" alt="" srcset="">
            </div>
            <div>
                <h2>
                    &#8358; 15,000
                </h2>
                <h4>Nigerian chin-chin</h4>
                <p>1KG</p>
                <div class="order-quantity">
                    <div class="order-button">
                        &#8722;
                    </div>
                    <div class="order-item-qty">
                        30
                    </div>
                    <div class="order-button">
                        &#43;
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="order-line"></div>
    <section class="cart-summary">
        <div class="cart-total">
            total: &#8358; 24,000
        </div>
        <div class="cart-confirm">
            confirm order
        </div>
    </section>
</section>

store/templates/product_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'navbar.html' %}
<body>
  <section>
    <div class="category-flex">
      <div class="img-div">
        <img src="{{category.imageURL}}" alt="">
      </div>
      <div class="text-div" style="background-color:{{category.color}};">
        <!-- Add background -->
        <h2>{{category.name}}</h2>
        <p>
          {{category.description}}
        </p>
      </div>
    </div>
    
    <div class="product-display">
      <div class="line"></div>
      
      <div class="product-main">
        {% for product in products %}
        <div class="product-card">
          <a href="">
          <div>
            <img src="../../static/images/shakti-rajpurohit-qczubsyHofQ-unsplash(1).png" alt="">
          </div>
          <div class="product-text">
            <h4>Chocolate</h4>
            <p>₦1000</p>
            <div>
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <div>[Reviews 49]</div>
            </div>
          </div>
          </a>
        </div>
        {% endfor %}
        
        <div class="product-card">
          <a href="{% url 'store:product_item' 'citrus-chin-chin' %}">
          <div>
            <img src="../../static/images/shakti-rajpurohit-qczubsyHofQ-unsplash(1).png" alt="">
          </div>
          <div class="product-text">
            <h4>Chocolate</h4>
            <p>₦1000</p>
            <div>
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <div>[Reviews 49]</div>
            </div>
          </div>
          </a>
        </div>
        <div class="product-card">
          <a href="">
          <div>
            <img src="../../static/images/shakti-rajpurohit-qczubsyHofQ-unsplash(1).png" alt="">
          </div>
          <div class="product-text">
            <h4>Chocolate</h4>
            <p>₦1000</p>
            <div>
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <div>[Reviews 49]</div>
            </div>
          </div>
          </a>
        </div>

        <div class="product-card">
          <a href="">
          <div>
            <img src="../../static/images/shakti-rajpurohit-qczubsyHofQ-unsplash(1).png" alt="">
          </div>
          <div class="product-text">
            <h4>Chocolate</h4>
            <p>₦1000</p>
            <div>
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <img  src="{% static 'images/star.svg' %}" alt="">
              <div>[Reviews 49]</div>
            </div>
          </div>
          </a>
        </div>

        <!-- <div class="scroll-div">
          <div class="scroll">
            <button><img src="../../static/images/arrow-left.svg" alt=""></button>
            <h4>1</h4>
            <button><img src="../../static/images/arrow-right.svg" alt=""></button>
          </div>
        </div> -->
      </div>
    </div>
  </section>
</body>
{% endblock %}
</html>